server:
  port: 8081
  session-timeout: 30
  tomcat.uri-encoding: UTF-8

spring:
  mail:
   host: smtp.163.com
   username: gzxiaoi@163.com
   password: sGzxiaoi123
   properties:
    mail:
     smtp:
      auth: true
      timeout: 25000

  thymeleaf:
    prefix: classpath:/templates/
  datasource:
        name: test
        url: jdbc:mysql://localhost:3306/su_manager?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml

